### ISSUE TITLE
Allow users to ignore/modify touch target sizes on certain elements

### ISSUE THREAD

**Issue by Caseysch** [microsoft/accessibility-insights-for-android-service#11]
## Is your feature request related to a problem? Please describe.
We chose to make the text in our react-native app selectable for copy/paste on long press (By using ReactNativeText components with "selectable" equal to true). Unfortunately, this results in all text being considered interactable and the number of errors from this hides actual errors I want to see.

## Describe the desired outcome
I would like to be able to ignore this specific error (touch target size on selectable text).

## Describe alternatives you've considered
Alternatively, we can turn off selectable text or reserve it for a select few lines of text that are important enough to meet the touch target size.

## Additional context
This accessibility scanner is currently consistent with the Accessibility Scanner app from Google, which also marks this text as violating touch targets.

**Comment by ferBonnin** [comment]
Hi @Caseysch thanks for the feature request!

We reviewed this feature request with the team and decided that this feature is out of scope. Having a good target size on these elements can help users select the right element and reduce errors and frustration also, introducing the ability to suppress rules in certain cases will mean that everyone running accessibility insights will get different results and expressing this adequately will require significant UI changes and will make the user experience more complex.
