### ISSUE TITLE
Questions regarding exporting of results

### ISSUE THREAD

**Issue by daphneyyt** [microsoft/accessibility-insights-for-android-service#170]
Hi Accessibility Insights team,

I have some questions regarding the results export function for Accessibility Insights For Android. 

**1) May we know is there any way to export the results in .xlsx (excel file) format?**
Currently, we understand we are able to access and download the HTML version of these results. We would like to check if there are other results export functions available.

**2) May we also know if there is any way to export/ download the target app screenshots from Accessibility Insights?**
Currently, we are manually taking screen captures of the target apps. So, we would like to know if a download option is available, which we are unaware of.

Thank you and we appreciate your reply.

Regards
Daphne

**Comment by sfoslund** [comment]
Hi @daphneyyt, thanks for using accessibility insights! To answer your questions:

1) No, we do not support exporting results to .xlsx files at this time. 

2) No, we do not have a way to export target app screenshots. 

We actually have 2 related issues already tracked in our other repo: [Add a screenshot in the Android and Web Automated checks report](https://github.com/microsoft/accessibility-insights-web/issues/2770) and [Export "as JSON" from FastPass ](https://github.com/microsoft/accessibility-insights-web/issues/5677). If you'd like this functionality to be added to accessibility insights, I would recommend commenting on those issues to voice support and bump them up on the team's priority list (and commenting on the second one to expand it's scope from just exporting as JSON to also exporting as .xlsx).

Does that answer your questions? Is there anything else I can help with or should we go ahead and close this issue?

**Comment by daphneyyt** [comment]
Hi @sfoslund thank you for responding to my queries quickly. Apologies for the late reply as my mailbox did not notify me of your response. 

Noted your suggestion to bump up the related issues. I'll check them out. You may close this ticket as well. Thank you!

**Comment by sfoslund** [comment]
Sounds good, thanks!
