### ISSUE TITLE
Screenshot fails on M1 Mac

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-for-android-service#172]
## Describe the bug

On an M1 Mac, when using the emulator, the service fails to take a screenshot. The screenshot succeeds when using a physical android device, so this is likely a bug in the emulator. Filing this bug to investigate whether that is the case, and if it is, create a minimal repro to file the bug with Android Studio.

After some investigation with @katydecorah, we know that the [original bitmap](https://github.com/microsoft/accessibility-insights-for-android-service/blob/main/AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/OnScreenshotAvailable.java#L74) that we get from the screenshot API is an empty image. However, when we tried to repro the same bug on a [different screenshot app](https://github.com/mtsahakis/MediaProjectionDemo), the screenshot was taken successfully, so the bug may only exist in some versions of Android, or when a screenshot is taken in the specific way that our service does.

### To Reproduce

**With the Accessibility Insights client:**
1. On an M1 Mac, start Android Studio
2. From the top menu, select run > Select device > device manager > Create device. Follow the steps to create a Pixel 3a emulator (with Android API 33).
3. Still in the device manager window, select the "run" icon next to the Pixel 3a device
4. Launch the Accessibility Insights for Android client. Follow the onscreen steps to connect to the emulator. (Note that if you already have the A11y Insights for Android service installed on the emulator, the client will force an update to the most recent production version, so the client cannot be used for dev testing the service)
5. Run an automated checks scan
6. Observe that the screenshot is blank

**Without the Accessibility Insights client:**
1. On an M1 Mac, open the project in Android Studio
2. From the top menu, select run > Select device > device manager > Create device. Follow the steps to create a Pixel 3a emulator (with Android API 33). Make sure this device is selected in the dropdown next to the green "run" triangle button.
7. Wait for the project to build
8. Add a debugging breakpoint in [onScreenshotAvailable.java](https://github.com/microsoft/accessibility-insights-for-android-service/blob/main/AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/OnScreenshotAvailable.java#L74) just after the bitmap is created
9. From the top menu, select run > debug
10. Start the Accessibility Insights service and allow screen recording permissions
11. From the top menu, select run > attach to debug process
12. Use ADB to trigger a [request to the service](https://github.com/microsoft/accessibility-insights-for-android-service#triggering-requests-in-adb) (`adb shell content read --uri content://com.microsoft.accessibilityinsightsforandroidservice/result`)
13. Execution should stop on the breakpoint you set in step 3
14. In the debug window, next to `bitmap,` click "view bitmap"
15. Observe that the window shows a blank image

## Expected behavior

We should be able to take a screenshot

## Screenshots

<img width="1271" alt="2022-08-22 at 3 56 PM" src="https://user-images.githubusercontent.com/55459788/187257086-fffcfd46-5be5-4733-b38f-4c7c825548de.png">

## Context (please complete the following information)

- Android Version: 13 (API 33)
- Service Version & Environment: 2.0.0 Production
- Target Application: Any

## Are you willing to submit a PR?

No (I don't have the device necessary to repro)

## Did you search for similar existing issues?

Yes

**Comment by DaveTryon** [comment]
We won't be fixing this
