### ISSUE TITLE
Accessibility Insights Screens Disconnecting

### ISSUE THREAD

**Issue by daphneyyt** [microsoft/accessibility-insights-for-android-service#61]
**We encourage tool related questions to be asked on stackoverflow.com and tagged with `accessibility-insights`.**

## Hi I have a query regarding Accessibility Insights For Android. We are running WCAG tests for a few mobile apps. However, we are encountering scenarios where the mobile app disconnects whenever we load a certain screen on the mobile app 

- Example 1: For App 1, Accessibility Insights disconnects when I try to load the Insert Credit Card page screen
- Example 2: For App 2, Accessibility Insights disconnects when I try to load the I load the FAQ page screen

However, all other screens works while scanning the apps within the same sitting. We have also tried scanning the same screens across a couple of laptops with the same problem. 

May I know what possible reasons could there be for such cases? Does it have to do with the codes done on the mobile app backend?

This is the screenshot received:
![image](https://user-images.githubusercontent.com/75086091/100370411-31b6c080-3041-11eb-9b3a-b415976c406c.png)

Appreciate your advice. Thank you!

**Comment by AhmedAbdoOrtiga** [comment]
@daphneyyt can you please add more info, what do you mean what do you mean by a credit card page and what which FAQ page you're mentioning?

**Comment by DaveTryon** [comment]
@daphneytt, we need more info before we can take any action here. Thanks!
