### ISSUE TITLE
API does not return results on Android 8.0

### ISSUE THREAD

**Issue by jalkire** [microsoft/accessibility-insights-for-android-service#8]
## Describe the bug
Calls to the API return "localhost didn’t send any data. ERR_EMPTY_RESPONSE" on Android 8.0 devices.

**To Reproduce**

1. Install and run the service on an Android 8.0 emulator
2. Go to http://localhost:62442/AccessibilityInsights/result
3. See no results

## Expected behavior
Results are returned. 

## Context (please complete the following information)

- Android Version: 8.0

**Comment by ferBonnin** [comment]
per conversation with Peter, should fix this

**Comment by waabid** [comment]
#12 should fix this issue.

**Comment by jalkire** [comment]
Validated on master.

**Comment by ferBonnin** [comment]
keeping in resolved until users can access the fix.

**Comment by ferBonnin** [comment]
this was validated during release v1.1 and its now in prod
