### ISSUE TITLE
focus tracking highlights are not vertically centered

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-for-android-service#95]
## Describe the bug

On some devices (I'm using a Samsung Galaxy Tab S4 but it's also occurred on others), the focus tracking highlights are not vertically centered on the View that received the focus. This may be related to differences in the heights of the top and bottom bars that exist on the display.

**To Reproduce**

1. Start AI-Android
2. Start tab stops tracking (I used calculator as my test app since the small buttons make it easy to spot the offset)
3. Tab around the app and compare the highlight circles
4. Compare the highlight positions to the View positions--they're horizontally centered, but not vertically centered (see screenshot):

## Expected behavior

Highlights should be vertically centered on the View

## Screenshots

![image](https://user-images.githubusercontent.com/45672944/113917179-bbb42a00-9795-11eb-86ff-7ff158f33b6a.png)

## Context (please complete the following information)

- Android Version: 
- Service Version & Environment: 
- Target Application: 

## Are you willing to submit a PR?
Yes

## Did you search for similar existing issues?
Yes

**Comment by ferBonnin** [comment]
per conversation with Peter, marking this as needs investigation and waiting on user feedback before deciding to address this

**Comment by ferBonnin** [comment]
per conversation with Peter,  closing since there hasnt been any user feedback, will reactivate if needed
